#!/usr/bin/env bash
set -ex

HERE=${BASH_SOURCE%/*}
parent=$(dirname $HERE)

docker build --tag bb8_metrics --file  $HERE/Dockerfile $HERE
docker run --rm \
    -p 5000:80 \
    -v $(realpath $parent/bb8):/usr/local/bin/bb8  \
    -v /var/run/docker.sock:/var/run/docker.sock \
    --detach \
    --name=bb8_metrics_1\
    bb8_metrics
