#!/usr/bin/env bash
set -e

HERE=${BASH_SOURCE%/*}

# Setup link
bb8_path=$(realpath ${HERE}/bb8)
link_path=/usr/local/bin/bb8
link_status=""

if [ -L $link_path ]; then
    link_status=$(readlink -- $link_path)
fi

if [ "$link_status" != "$bb8_path" ]; then
    echo "Creating symlink at $link_path"
    ln -sf $bb8_path $link_path
fi
