#!/usr/bin/env python3
import os

contents = """#!/usr/bin/env bash
bb8 backup
"""
path = "/etc/cron.hourly/bb8"

current = None
if os.path.isfile(path):
    with open(path, 'r') as f:
        current = f.read()

if current == contents:
    print("Backup already scheduled")
else:
    with open(path, 'w') as f:
        f.write(contents)
    os.chmod(path, 0o755)
    print("Scheduled hourly backups ☺️")
