#!/usr/bin/env bash
set -ex

parent=$(dirname $PWD)

docker build --tag bb8_metrics .
docker run --rm \
    -p 5000:80 \
    -v $parent/bb8:/usr/local/bin/bb8  \
    -v /var/run/docker.sock:/var/run/docker.sock \
    --detach \
    bb8_metrics
